language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t forrest1102/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true forrest1102/docker-react npm run test